tap "derailed/k9s"
tap "homebrew/bundle"
tap "julien040/gut"
tap "remotemobprogramming/brew"
brew "asdf"
brew "atuin"
brew "bat"
brew "bfg"
brew "btop"
brew "direnv"
brew "docker"
brew "doggo"
brew "eza"
brew "ffmpeg"
brew "fish"
brew "fzf"
brew "gh"
brew "git"
brew "git-delta"
brew "git-extras"
brew "git-lfs"
brew "glab"
brew "glow"
brew "gum"
brew "helm"
brew "htop"
brew "httpie"
brew "iproute2mac"
brew "jj"
brew "jq"
brew "kubernetes-cli"
brew "kubectx"
brew "mas"
brew "mkcert"
brew "nmap"
brew "nss"
brew "pandoc"
brew "pipx"
brew "pnpm"
brew "ripgrep"
brew "sops"
brew "stow"
brew "tailscale"
brew "telnet"
brew "tfenv"
brew "topgrade"
brew "tree"
brew "vault"
brew "wget"
brew "yarn"
brew "zoxide"
brew "zsh"
brew "derailed/k9s/k9s"
brew "remotemobprogramming/brew/mob"
cask "1password"
cask "1password-cli"
cask "alt-tab"
cask "ankerwork"
cask "arc"
cask "betterdisplay"
cask "box-drive"
cask "chatgpt"
cask "citrix-workspace"
cask "elgato-wave-link"
cask "firefox"
cask "firefox@developer-edition"
cask "font-fantasque-sans-mono-nerd-font"
cask "font-fira-code-nerd-font"
cask "google-chrome@canary"
cask "gpg-suite"
cask "heptabase"
cask "istat-menus"
cask "iterm2"
cask "jetbrains-toolbox"
cask "jordanbaird-ice"
cask "macfuse"
cask "macupdater"
cask "mediamate"
cask "microsoft-auto-update"
cask "microsoft-excel"
cask "microsoft-outlook"
cask "microsoft-powerpoint"
cask "microsoft-teams"
cask "microsoft-word"
cask "miro"
cask "msty"
cask "musescore"
cask "nordvpn"
cask "notion"
cask "obsidian"
cask "orbstack"
cask "parallels"
cask "pitch"
cask "raindropio"
cask "raycast"
cask "reader"
cask "setapp"
cask "slack"
cask "soundsource"
cask "steam"
cask "swish"
cask "teamviewer"
cask "thunderbird"
cask "todoist"
cask "tor-browser"
cask "tradingview"
cask "vmware-fusion"
cask "wezterm"
cask "zed"
cask "zoom"
mas "1Password for Safari", id: 1569813296
mas "Compressor", id: 424390742
mas "Final Cut Pro", id: 424389933
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Local Calendar Sync", id: 6478960914
mas "Logic Pro", id: 634148309
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Parcel", id: 639968404
mas "PDF Expert", id: 1055273043
mas "Reeder", id: 6475002485
mas "Shortery", id: 1594183810
mas "Tailscale", id: 1475387142
mas "TestFlight", id: 899247664
