tap "homebrew/bundle"
tap "homebrew/cask-fonts"
brew "asdf"
brew "atuin"
brew "bat"
brew "docker"
brew "eza"
brew "ffmpeg"
brew "fish"
brew "fzf"
brew "gh"
brew "git-extras"
brew "git-lfs"
brew "gum"
brew "htop"
brew "httpie"
brew "mas"
brew "nmap"
brew "pnpm"
brew "ripgrep"
brew "stow"
brew "tailscale"
brew "topgrade"
brew "tree"
brew "wget"
brew "yt-dlp"
brew "z"
brew "zoxide"
cask "1password"
cask "1password-cli"
cask "adobe-acrobat-reader"
cask "arc"
cask "bartender"
cask "betterdisplay"
cask "busycal"
cask "discord"
cask "firefox"
cask "font-fira-code-nerd-font"
cask "gpg-suite"
cask "iterm2"
cask "jetbrains-toolbox"
cask "kindle"
cask "macfuse"
cask "mediamate"
cask "notion"
cask "notion-calendar"
cask "nvidia-geforce-now"
cask "orbstack"
cask "raycast"
cask "reader"
cask "soundsource"
cask "steam"
cask "sunsama"
cask "swish"
cask "telegram"
cask "todoist"
cask "tradingview"
cask "warp"
cask "zed"
mas "1Password for Safari", id: 1569813296
mas "Notchmeister", id: 1599169747
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Parcel", id: 639968404
mas "Tailscale", id: 1475387142
mas "TestFlight", id: 899247664
mas "Xcode", id: 497799835
