complete -c rip -n "__fish_use_subcommand" -l graveyard -d 'Directory where deleted files rest' -r -F
complete -c rip -n "__fish_use_subcommand" -s d -l decompose -d 'Permanently deletes the graveyard'
complete -c rip -n "__fish_use_subcommand" -s s -l seance -d 'Prints files that were deleted in the current directory'
complete -c rip -n "__fish_use_subcommand" -s u -l unbury -d 'Restore the specified files or the last file if none are specified'
complete -c rip -n "__fish_use_subcommand" -s i -l inspect -d 'Print some info about TARGET before burying'
complete -c rip -n "__fish_use_subcommand" -s h -l help -d 'Print help'
complete -c rip -n "__fish_use_subcommand" -s V -l version -d 'Print version'
complete -c rip -n "__fish_use_subcommand" -a "completions" -d 'Generate shell completions file'
complete -c rip -n "__fish_use_subcommand" -a "graveyard" -d 'Print the graveyard path'
complete -c rip -n "__fish_use_subcommand" -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c rip -n "__fish_seen_subcommand_from completions" -s h -l help -d 'Print help'
complete -c rip -n "__fish_seen_subcommand_from graveyard" -s s -l seance -d 'Get the graveyard subdirectory of the current directory'
complete -c rip -n "__fish_seen_subcommand_from graveyard" -s h -l help -d 'Print help'
complete -c rip -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from completions graveyard help" -f -a "completions" -d 'Generate shell completions file'
complete -c rip -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from completions graveyard help" -f -a "graveyard" -d 'Print the graveyard path'
complete -c rip -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from completions graveyard help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
